# Generated by Django 4.0.1 on 2022-01-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=200)),
                ('turu', models.CharField(max_length=200)),
                ('kapasite', models.IntegerField()),
                ('tarih', models.DateField()),
            ],
        ),
    ]
